title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     lab-starter
  repo:     lab-starter

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo



# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: 
- title: Know yourself
  description: The key to becoming a new person is to undertand yourself.
  event: pull_request
  actions: # a list of the actions that will occur when the step is triggered by an event
  type: respond
  with: 01_nice-work.md

- title: Assign yourself
  description: Assign the first issue to yourself.
  event: issues.assigned
  link: 'https://github.com/amrbakouban/lab-starter/issues/1'
  actions:
  type: respond
  with: 01_nice-work.md
    
- title: Make goals for improvement
  description: Making goals is a a big step for improvment
  event: status
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
 - title: # Act upon your goals
  description: Work towards achieving your goals and remember that failure is a step towards success.
  event: pull_request
  actions:
  type: respond
  with: 01_nice-work.md
    

# Step 4: 
 - title: Work hard everyday
   description: Make sure you're working hard everyday and be committed to yourself.
   event: issue_commented.created
   actions:
   type: respond
   with: 01_nice-work.md
    

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
 - title:  Communicate with others
  description: Surrounding yourself with people you idolize to be can be the cherry on top.
  event: status
  actions:
  type: respond
  with: 01_nice-work.md
    
